version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=realleads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/usr/src/app/src

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app

volumes:
  db_data:
