services:
  - type: web
    name: realestate-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node src/server.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  - type: web
    name: realestate-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/out
    plan: free

databases:
  - name: realestate-db
    plan: free
